### PR TITLE
docusaurus upgrade

### PR DESCRIPTION
**Pull request by slorber**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @slorber, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;data.home-assistant#83).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by slorber** [comment]
@TomBrien Docusaurus deps should be upgraded all at once, not one by one.

image


alpha 61 is not necessarily compatible with alpha 62

**Comment by TomBrien** [comment]
Hi @slorber thanks for this. I think the root of this comes from letting dependabot handle the updates for us. This is the first time we've run into an issue updating the two separately (although there is normally an order needed). I wonder if the peer dependency on docusarus/core [https://github.com/facebook/docusaurus/blob/149d82c730c73ef9cad24264abd329a660c460da/packages/docusaurus-preset-classic/package.json#L22](docusaurus-preset-classic) should be updated to reflect matching the alpha version. Would you like me to open an issue on the Docusaurus repo for that.

For this, if you're happy to sign the CLA for Home Assistant I can merge this now. If you would prefer to not just close this an I will recreate. Thanks again :).

**Comment by slorber** [comment]
Signed,

Actually I thought it was fixed by https://github.com/facebook/docusaurus/pull/3162/files but apparently not 🤪

**Comment by TomBrien** [comment]
Thanks. I'll put in a issue on the `peerDependency` now. Cheers for looking into this. Really went above and beyond there.

**Review by TomBrien — APPROVED** [review]

**Pull request merged**
